### ISSUE TITLE
Removing the PyCrypto dependency in favour of PyCA's cryptography.

### ISSUE THREAD

**Issue by Ayrx** [Roguelazer/onepasswordpy#10]
In #8, PyCA's cryptography has been added as a dependency. Are you in favour of porting all the symmetric crypto code (I see usage of MD5, the various SHA hashes, AES and HMAC, all of which PyCA's cryptography supports) to PyCA's cryptography thereby removing the dependency on PyCrypto?

I am willing to do the porting work. (Full disclosure: I'm a PyCA's cryptography developer) :)

**Comment by RazerM** [comment]
@Ayrx I have already ported, I will push my code and open a pull request.

**Comment by Ayrx** [comment]
@RazerM Cool!

**Comment by RazerM** [comment]
See pull request #11
